- id: michael-m.-hoffman
- id: current-positions
- id: education
- id: publications
- id: publications-journal
- id: publications-conference-proceedings
- id: publications-submitted
- id: publications-theses
- id: intellectual-property
- id: recognitions
- id: recognitions-other-scholarships-and-awards
- id: recognitions-honors
- id: funding
- id: funding-lead-principal-investigator
- id: funding-co-principal-investigator
- id: funding-co-investigator
- id: presentations
- id: presentations-invitedkeynote
# - id: presentations-invitedkeynote-local
- id: presentations-conference-selected-from-abstracts
# - id: presentations-conference-selected-from-abstracts-trainee
- id: presentations-invited-panelist
# - id: presentations-invited-panelist-local
- id: presentations-other-teaching
- id: presentations-other-seminars
# - id: presentations-other-seminars-local
- id: professional-activities
- id: professional-activities-conference-organizer
- id: professional-activities-session-chair
- id: professional-activities-funding-review
- id: professional-activities-manuscript-review
- id: professional-activities-external-advisory-committees
- id: professional-activities-external-advisory-workshops-and-panels
- id: professional-activities-society-leadership-positions
- id: professional-activities-consortium-leadership-positions
- id: professional-activities-institutional-leadership-positions-and-committees
- id: professional-activities-student-committees-and-examinations
- id: professional-activities-memberships
# - id: excluding professional-activities-memberships-local
- id: prior-positions
- id: trainees-and-staff-supervised
- id: trainees-and-staff-supervised-current
- id: trainees-and-staff-supervised-past
- id: media-coverage
- id: media-coverage-interviews
- id: media-coverage-meeting-reports
- id: citizenship-and-immigration
